a = input('Digite algo: ')

print('O tipo primitivo valor é ' ,type(a))
print('Só tem espacos', a.isspace())
print('E um número', a.isnumeric())
print('É alfabético ', a.isalpha())
print('É alfanumérico', a.isalnum())
print('Está e maiusculas?', a.isupper())
print('Está e minusculas?', a.islower())
print('Está capitalizada?', a.istitle())
